name: plusminus
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  collection:
  dartea:
  fluttertoast:
  webview_flutter: ^0.3.16
  shared_preferences: ^0.5.4+6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

