name: plusminus
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  collection:

  # Redux dependencies
  redux: ^3.0.0
  flutter_redux: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

